import {
  backmarkerBudget,
  reverseConstructorPoints,
  scoreDriver,
  type DriverRaceInput,
  type ScoreBreakdown,
} from "./scoring";
import type { RosterSelection } from "./roster";
import { applyChips, type ActiveChips } from "./chips";

/**
 * Scoring a roster for one round.
 *
 * Pure: everything the calculation needs arrives in `RoundFacts`, so a whole
 * season can be scored offline against ingested data without touching the
 * database.
 */

export interface RoundFacts {
  /** Race inputs per driver, keyed by jolpica driver id. */
  drivers: ReadonlyMap<string, DriverRaceInput>;
  /** Which drivers each constructor fielded this round. */
  constructorDrivers: ReadonlyMap<string, readonly string[]>;
  /** Constructors ranked by how their cars finished, best first. */
  constructorRanking: readonly string[];
  /**
   * Cars entered this round. It is what the backmarker slot pays for a last
   * place, and therefore what it pays for a retirement.
   */
  fieldSize: number;
}

export interface SlotScore {
  slot: string;
  competitorId: string;
  points: number;
  breakdown?: ScoreBreakdown;
}

export interface RosterScore {
  slots: SlotScore[];
  /** Fantasy points. Excludes the backmarker, which pays cost cap instead. */
  points: number;
  /** Cost cap generated by the backmarker slot. */
  budget: number;
}

/**
 * A constructor's fantasy score.
 *
 * Taken as the sum of its drivers' scores, matching how the official game
 * derives the bulk of a constructor's total. The official game adds
 * constructor-only bonuses (a Q3-progression bonus and pit-stop times); those
 * are deliberately left out of v1 rather than half-implemented, since the
 * pit-stop bonus depends on stationary times we established are not available
 * from either upstream source.
 */
export function constructorScore(constructorId: string, facts: RoundFacts): number {
  const drivers = facts.constructorDrivers.get(constructorId) ?? [];
  return drivers.reduce((total, driverId) => {
    const input = facts.drivers.get(driverId);
    return total + (input ? scoreDriver(input).total : 0);
  }, 0);
}

/**
 * Scores a complete roster.
 *
 * A missing competitor scores nothing rather than throwing: a driver can be
 * replaced mid-season, and a roster picked before that should still score.
 */
export function scoreRoster(
  selection: RosterSelection,
  facts: RoundFacts,
  chips: ActiveChips = {},
): RosterScore {
  const slots: SlotScore[] = [];

  const scoreDriverSlot = (slot: string, driverId: string) => {
    const input = facts.drivers.get(driverId);
    const breakdown = input ? scoreDriver(input) : undefined;
    slots.push({
      slot,
      competitorId: driverId,
      points: breakdown?.total ?? 0,
      breakdown,
    });
  };

  selection.top.forEach((driverId) => scoreDriverSlot("driver_top", driverId));
  selection.mid.forEach((driverId) => scoreDriverSlot("driver_mid", driverId));

  // The backmarker scores no points at all; it pays cost cap instead (spec §4).
  let budget = 0;
  if (selection.backmarker) {
    const input = facts.drivers.get(selection.backmarker);
    budget = input
      ? backmarkerBudget(input.finishPosition, input.classification, facts.fieldSize)
      : 0;
    slots.push({ slot: "driver_backmarker", competitorId: selection.backmarker, points: 0 });
  }

  for (const constructorId of selection.constructors) {
    slots.push({
      slot: "constructor",
      competitorId: constructorId,
      points: constructorScore(constructorId, facts),
    });
  }

  if (selection.reverseConstructor) {
    slots.push({
      slot: "constructor_reverse",
      competitorId: selection.reverseConstructor,
      points: reverseConstructorPoints(
        selection.reverseConstructor,
        facts.constructorRanking,
      ),
    });
  }

  // Chips are applied to the finished slot scores rather than folded into the
  // per-driver calculation, so a multiplier acts on the driver's whole result
  // (including penalties) exactly as a player would expect.
  const withChips = applyChips(slots, chips);
  const scored = slots.map((slot, index) => ({ ...slot, points: withChips[index].points }));

  return {
    slots: scored,
    points: Math.round(scored.reduce((total, slot) => total + slot.points, 0) * 100) / 100,
    budget,
  };
}

export interface DuelOutcome {
  homeMemberId: string;
  awayMemberId: string;
  homePoints: number;
  awayPoints: number;
  /** Win 1, draw 0.5, loss 0 — the standard convention. */
  homeDuelPoints: number;
  awayDuelPoints: number;
}

/**
 * Resolves one head-to-head.
 *
 * A member with no roster scores zero, which loses to anyone who fielded one.
 * That makes a forfeit rule unnecessary: not picking is already the worst
 * possible outcome, and adding a separate penalty would punish the same
 * omission twice.
 *
 * A draw splits the point rather than voiding it, so a tied week still counts
 * as something in the standings.
 */
export function resolveDuel(
  homeMemberId: string,
  awayMemberId: string,
  scores: ReadonlyMap<string, number>,
): DuelOutcome {
  const homePoints = scores.get(homeMemberId) ?? 0;
  const awayPoints = scores.get(awayMemberId) ?? 0;

  let homeDuelPoints = 0.5;
  let awayDuelPoints = 0.5;
  if (homePoints > awayPoints) {
    homeDuelPoints = 1;
    awayDuelPoints = 0;
  } else if (awayPoints > homePoints) {
    homeDuelPoints = 0;
    awayDuelPoints = 1;
  }

  return { homeMemberId, awayMemberId, homePoints, awayPoints, homeDuelPoints, awayDuelPoints };
}
