import {
  backmarkerPoints,
  reverseConstructorPoints,
  scoreDriver,
  type DriverRaceInput,
  type ScoreBreakdown,
} from "./scoring";
import type { RosterSelection } from "./roster";
import { applyChips, type ActiveChips } from "./chips";

/**
 * Scoring a roster for one round.
 *
 * Pure: everything the calculation needs arrives in `RoundFacts`, so a whole
 * season can be scored offline against ingested data without touching the
 * database.
 */

export interface RoundFacts {
  /** Race inputs per driver, keyed by jolpica driver id. */
  drivers: ReadonlyMap<string, DriverRaceInput>;
  /** Which drivers each constructor fielded this round. */
  constructorDrivers: ReadonlyMap<string, readonly string[]>;
  /** Constructors ranked by how their cars finished, best first. */
  constructorRanking: readonly string[];
  /**
   * Cars entered this round. It is what the backmarker slot pays for a last
   * place, and therefore what it pays for a retirement.
   */
  fieldSize: number;
  /**
   * Whether the backmarker pays points this round or cost cap.
   *
   * Decided by the caller from the round, so this stays a pure scorer with no
   * opinion about dates. See `backmarkerScoresPoints`.
   */
  backmarkerScoresPoints: boolean;
}

/**
 * One contributing line in a slot's score, ready to be read rather than
 * recomputed.
 *
 * Deliberately flat and presentation-neutral: a driver's line is a scoring
 * component ("Race", "Overtakes"), a team's line is one of its cars. The label
 * is the final word for components; for a car it is the driver id, which only
 * the page can turn into a name, so `driverId` marks that case rather than
 * making every reader guess which kind of label it is holding.
 */
export interface SlotBreakdownLine {
  label: string;
  /** Set when the line is one of a team's cars; `label` is then the same id. */
  driverId?: string;
  points: number;
}

/**
 * How a slot's score came together, in the order it should be read.
 *
 * `subtotal` is before any chip: the multiplier is on the pick's badge already,
 * and the difference between this and the stored points is what the chip did.
 * A slot nobody can break down — a backmarker, or a pick with no result —
 * carries an empty list and says why in `note`.
 */
export interface SlotBreakdown {
  lines: SlotBreakdownLine[];
  subtotal: number;
  note?: string;
}

export interface SlotScore {
  slot: string;
  competitorId: string;
  points: number;
  breakdown?: ScoreBreakdown;
  /** The same score told as lines, for showing a player where it came from. */
  detail: SlotBreakdown;
}

export interface RosterScore {
  slots: SlotScore[];
  /**
   * Fantasy points. Includes the backmarker from the round it started scoring
   * points; before that the slot contributes nothing here and pays `budget`.
   */
  points: number;
  /** Cost cap generated by the backmarker, on the rounds where it still pays it. */
  budget: number;
}

/**
 * A constructor's fantasy score.
 *
 * Taken as the sum of its drivers' scores, matching how the official game
 * derives the bulk of a constructor's total. The official game adds
 * constructor-only bonuses (a Q3-progression bonus and pit-stop times); those
 * are deliberately left out of v1 rather than half-implemented, since the
 * pit-stop bonus depends on stationary times we established are not available
 * from either upstream source.
 */
export function constructorScore(constructorId: string, facts: RoundFacts): number {
  const drivers = facts.constructorDrivers.get(constructorId) ?? [];
  return drivers.reduce((total, driverId) => {
    const input = facts.drivers.get(driverId);
    return total + (input ? scoreDriver(input).total : 0);
  }, 0);
}

/**
 * Scores a complete roster.
 *
 * A missing competitor scores nothing rather than throwing: a driver can be
 * replaced mid-season, and a roster picked before that should still score.
 */
/**
 * A driver's scoring components as readable lines, zeros left out.
 *
 * Everything that scored nothing is dropped: a list of ten rows where eight say
 * 0 buries the two that explain the score. Penalties are the exception worth
 * naming — they are the reason a good race can still read badly — but they are
 * only ever non-zero when something went wrong, so the same rule covers them.
 *
 * Ordered as the weekend ran rather than by size, so the list can be read as a
 * story: Saturday, then Sunday, then what was added or taken off at the end.
 */
function driverLines(breakdown: ScoreBreakdown): SlotBreakdownLine[] {
  const labels: [keyof ScoreBreakdown, string][] = [
    ["qualifying", "Qualifying"],
    ["qualifyingProgress", "Qualifying progress"],
    ["sprint", "Sprint"],
    ["race", "Race finish"],
    ["positionsGained", "Positions gained"],
    ["overtakes", "Overtakes"],
    ["fastestLap", "Fastest lap"],
    ["driverOfTheDay", "Driver of the day"],
    ["teammate", "Beat teammate"],
    ["penalties", "Penalties"],
  ];

  return labels
    .map(([key, label]) => ({ label, points: breakdown[key] }))
    .filter((line) => line.points !== 0);
}

export function scoreRoster(
  selection: RosterSelection,
  facts: RoundFacts,
  chips: ActiveChips = {},
): RosterScore {
  const slots: SlotScore[] = [];

  const scoreDriverSlot = (slot: string, driverId: string) => {
    const input = facts.drivers.get(driverId);
    const breakdown = input ? scoreDriver(input) : undefined;
    slots.push({
      slot,
      competitorId: driverId,
      points: breakdown?.total ?? 0,
      breakdown,
      detail: breakdown
        ? { lines: driverLines(breakdown), subtotal: breakdown.total }
        : {
            lines: [],
            subtotal: 0,
            // A driver in the field would have a result, so this is one who was
            // not: withdrawn, or never entered. Saying nothing here would leave
            // a bare 0 looking like a scoring failure.
            note: "Did not take part in this round.",
          },
    });
  };

  selection.top.forEach((driverId) => scoreDriverSlot("driver_top", driverId));
  selection.mid.forEach((driverId) => scoreDriverSlot("driver_mid", driverId));

  // The backmarker is scored in reverse either way — one per place from the
  // front, so a slower car is worth more. What changed at
  // `BACKMARKER_POINTS_FROM` is the currency: points now, cost cap on the
  // rounds before it, which are left as they were settled.
  let budget = 0;
  if (selection.backmarker) {
    const input = facts.drivers.get(selection.backmarker);
    const paid = input
      ? backmarkerPoints(input.finishPosition, input.classification, facts.fieldSize)
      : 0;
    const asPoints = facts.backmarkerScoresPoints;
    if (!asPoints) budget = paid;

    const placing = !input
      ? null
      : input.classification === "disqualified"
        ? "Disqualified"
        : paid === facts.fieldSize
          ? `Last of ${facts.fieldSize}, or did not finish`
          : `Finished ${paid} of ${facts.fieldSize}`;

    slots.push({
      slot: "driver_backmarker",
      competitorId: selection.backmarker,
      points: asPoints ? paid : 0,
      detail: {
        lines: asPoints && placing ? [{ label: placing, points: paid }] : [],
        subtotal: asPoints ? paid : 0,
        note: !input
          ? "Did not take part in this round."
          : asPoints
            ? "The backmarker pays one point per place from the front, so a slower car is worth more. A disqualification pays nothing."
            : `On this round the backmarker still paid cost cap rather than points. ${placing} — earned ${paid}.`,
      },
    });
  }

  for (const constructorId of selection.constructors) {
    // A team's score is its cars added up, so its cars are the breakdown. Two
    // lines that sum to the total is the whole explanation.
    const seats = facts.constructorDrivers.get(constructorId) ?? [];
    const lines = seats.map((driverId) => ({
      label: driverId,
      driverId,
      points: facts.drivers.get(driverId) ? scoreDriver(facts.drivers.get(driverId)!).total : 0,
    }));

    slots.push({
      slot: "constructor",
      competitorId: constructorId,
      points: constructorScore(constructorId, facts),
      detail: {
        lines,
        subtotal: constructorScore(constructorId, facts),
        note: lines.length === 0 ? "No cars classified for this team." : undefined,
      },
    });
  }

  if (selection.reverseConstructor) {
    const placing = facts.constructorRanking.indexOf(selection.reverseConstructor);
    const points = reverseConstructorPoints(
      selection.reverseConstructor,
      facts.constructorRanking,
    );

    slots.push({
      slot: "constructor_reverse",
      competitorId: selection.reverseConstructor,
      points,
      detail: {
        lines:
          placing === -1
            ? []
            : [{ label: `Finished ${placing + 1} of ${facts.constructorRanking.length} teams`, points }],
        subtotal: points,
        // The slot pays for being slow, which is the opposite of every other
        // row on the card and worth saying where the number is read.
        note:
          placing === -1
            ? "This team was not ranked on race pace this round."
            : "The reverse slot pays one point per place from the front, so a slower team is worth more.",
      },
    });
  }

  // Chips are applied to the finished slot scores rather than folded into the
  // per-driver calculation, so a multiplier acts on the driver's whole result
  // (including penalties) exactly as a player would expect.
  const withChips = applyChips(slots, chips);
  const scored = slots.map((slot, index) => ({ ...slot, points: withChips[index].points }));

  return {
    slots: scored,
    points: Math.round(scored.reduce((total, slot) => total + slot.points, 0) * 100) / 100,
    budget,
  };
}

export interface DuelOutcome {
  homeMemberId: string;
  awayMemberId: string;
  homePoints: number;
  awayPoints: number;
  /** Win 1, draw 0.5, loss 0 — the standard convention. */
  homeDuelPoints: number;
  awayDuelPoints: number;
}

/**
 * Resolves one head-to-head.
 *
 * A member with no roster scores zero, which loses to anyone who fielded one.
 * That makes a forfeit rule unnecessary: not picking is already the worst
 * possible outcome, and adding a separate penalty would punish the same
 * omission twice.
 *
 * A draw splits the point rather than voiding it, so a tied week still counts
 * as something in the standings.
 */
export function resolveDuel(
  homeMemberId: string,
  awayMemberId: string,
  scores: ReadonlyMap<string, number>,
): DuelOutcome {
  const homePoints = scores.get(homeMemberId) ?? 0;
  const awayPoints = scores.get(awayMemberId) ?? 0;

  let homeDuelPoints = 0.5;
  let awayDuelPoints = 0.5;
  if (homePoints > awayPoints) {
    homeDuelPoints = 1;
    awayDuelPoints = 0;
  } else if (awayPoints > homePoints) {
    homeDuelPoints = 0;
    awayDuelPoints = 1;
  }

  return { homeMemberId, awayMemberId, homePoints, awayPoints, homeDuelPoints, awayDuelPoints };
}
