/**
 * Clears a league's scored rounds before a given round.
 *
 *   npm run clear-early-rounds -- OgerF1 14
 *
 * For starting a league part-way into a real season: everyone begins level at
 * the named round, and whatever was scored before it stops counting.
 *
 * It removes two things, and needs to remove both. The scores are the point;
 * the rosters are what would otherwise put them straight back, because the
 * nightly job re-scores every ingested round that has a roster behind it.
 *
 * It deliberately leaves the cost cap alone. Purchases, price drift, backmarker
 * payouts and chip buys are money that was really spent and in some cases
 * turned into chips that are still held — rewriting that would take away things
 * members own. So a league cleared this way keeps its bank and loses its
 * scoreboard, which is the split that matches "start again from here".
 *
 * Destructive and not reversible. The rosters it deletes can be regenerated by
 * `npm run seed-league` only if they were seeded in the first place.
 */

import { createAdminClient, loadLocalEnv } from "../src/lib/supabase/admin";

loadLocalEnv();

async function main(): Promise<void> {
  const leagueName = process.argv[2];
  const fromRound = Number(process.argv[3]);

  if (!leagueName || !Number.isFinite(fromRound)) {
    console.log("Usage: npm run clear-early-rounds -- <league name> <first round to keep>");
    return;
  }

  const supabase = createAdminClient();

  const { data: league, error: leagueError } = await supabase
    .from("leagues")
    .select("id, name, season")
    .eq("name", leagueName)
    .maybeSingle();

  if (leagueError || !league) {
    console.log(`No league called ${leagueName}: ${leagueError?.message ?? "not found"}`);
    return;
  }

  const { data: members } = await supabase
    .from("league_members")
    .select("id")
    .eq("league_id", league.id);
  const memberIds = (members ?? []).map((member) => member.id);

  if (memberIds.length === 0) {
    console.log(`${league.name} has no members.`);
    return;
  }

  console.log(
    `${league.name} (${league.season}): clearing rounds before ${fromRound} for ${memberIds.length} member(s)`,
  );

  const { error: scoreError, count: scores } = await supabase
    .from("round_scores")
    .delete({ count: "exact" })
    .eq("season", league.season)
    .in("member_id", memberIds)
    .lt("round", fromRound);
  if (scoreError) throw new Error(`Could not clear scores: ${scoreError.message}`);

  const { error: rosterError, count: rosters } = await supabase
    .from("rosters")
    .delete({ count: "exact" })
    .eq("season", league.season)
    .in("member_id", memberIds)
    .lt("round", fromRound);
  if (rosterError) throw new Error(`Could not clear rosters: ${rosterError.message}`);

  console.log(`  round_scores removed  ${scores ?? 0}`);
  console.log(`  rosters removed       ${rosters ?? 0}`);
  console.log("  cost cap left untouched");
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
