#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# The app reads .env.local, so that is where existing values are found. Without
# this the wizard would offer no defaults and ask you to re-fetch keys you
# already have on disk.
ENV_FILE=".env.local"

REPO="Peofesor/F1-Fantasy"
SUPABASE_REF="cffgnedqsxfrgruevkvl"
SUPABASE="https://supabase.com/dashboard/project/$SUPABASE_REF"

# Windows: explorer.exe exits 1 even when it opens the page perfectly well — a
# long-standing quirk. The library reads that as failure and would print
# "couldn't open a browser" on all nine stages while the browser sat there with
# the page open. Overridden here rather than in the library above, which is
# shared and must stay identical across wizards.
if command -v explorer.exe >/dev/null 2>&1 && ! command -v wslview >/dev/null 2>&1; then
  open_url() {
    printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$1"
    explorer.exe "$1" >/dev/null 2>&1 || true
  }
fi

banner "Deploy F1 Fantasy to Vercel"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the things that would otherwise waste your time later."
printf '\n'

ok=1

if [[ -f "$ENV_FILE" ]]; then
  printf '  %s✓%s %s exists\n' "$GREEN" "$RESET" "$ENV_FILE"
else
  warn "$ENV_FILE is missing — copy .env.example and fill it in first"
  ok=0
fi

for key in NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_ANON_KEY SUPABASE_SERVICE_ROLE_KEY; do
  if grep -q "^${key}=." "$ENV_FILE" 2>/dev/null; then
    printf '  %s✓%s %s is set\n' "$GREEN" "$RESET" "$key"
  else
    warn "$key is missing from $ENV_FILE"
    ok=0
  fi
done

if [[ -z "$(git status --porcelain --untracked-files=no 2>/dev/null)" ]]; then
  printf '  %s✓%s working tree is clean\n' "$GREEN" "$RESET"
else
  warn "uncommitted changes — Vercel deploys what is pushed, not what is on disk"
fi

# Vercel builds from the remote, so anything unpushed simply will not deploy.
if [[ -z "$(git log --oneline '@{u}..HEAD' 2>/dev/null)" ]]; then
  printf '  %s✓%s everything is pushed\n' "$GREEN" "$RESET"
else
  warn "you have unpushed commits — run: git push"
  ok=0
fi

if (( ok == 0 )); then
  printf '\n'
  warn "fix the above, then run this again"
  exit 1
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Vercel: import the repository"
say "Vercel rebuilds on every push and runs the server side of the app."
open_url "https://vercel.com/new"
step "Sign in with GitHub if you have not already."
step "Find $REPO in the list and click Import."
step "Leave every build setting alone — Next.js is detected."
printf '\n'
warn "Do not deploy yet."
say "The next stage adds the environment variables, and a build without"
say "them will fail."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Vercel: environment variables"
say "Three values, all of them already in your $ENV_FILE."
printf '\n'

# The first two are printed because both are public by design: the URL
# identifies the project and the anon key is constrained by row-level security.
# The service-role key is deliberately not printed — it bypasses RLS, so it is
# copied from the file rather than left sitting in a terminal buffer.
step "NEXT_PUBLIC_SUPABASE_URL"
printf '    %s%s%s\n' "$DIM" "$(grep '^NEXT_PUBLIC_SUPABASE_URL=' "$ENV_FILE" | cut -d= -f2-)" "$RESET"
step "NEXT_PUBLIC_SUPABASE_ANON_KEY"
printf '    %s%s…%s\n' "$DIM" "$(grep '^NEXT_PUBLIC_SUPABASE_ANON_KEY=' "$ENV_FILE" | cut -d= -f2- | cut -c1-28)" "$RESET"
step "SUPABASE_SERVICE_ROLE_KEY"
printf '    %s(not shown — copy it out of %s)%s\n' "$DIM" "$ENV_FILE" "$RESET"

printf '\n'
say "On the import screen, expand Environment Variables and add all three."
say "Tick both Production and Preview for each one."
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Vercel: deploy, then tell me the address"
step "Click Deploy and wait for the build — about a minute."
step "Copy the production domain from the deployment page."
printf '\n'
warn "Your own domain, not an example — f1-fantasy.vercel.app belongs to"
warn "someone else's project and will answer, misleadingly, like a real app."
printf '\n'
# No sample URL in the prompt: the obvious one is taken, and pasting an
# example that answers is worse than pasting one that does not.
ask VERCEL_URL "Production URL:"

VERCEL_URL="${VERCEL_URL%/}"
if [[ "$VERCEL_URL" != http* ]]; then
  VERCEL_URL="https://$VERCEL_URL"
fi

# Checked now rather than at the end: every remaining stage points another
# service at this address, and a typo here is expensive to unpick afterwards.
code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 "$VERCEL_URL/rules" || echo 000)
if [[ "$code" == "200" ]]; then
  printf '  %s✓%s %s/rules answered 200\n' "$GREEN" "$RESET" "$VERCEL_URL"
else
  warn "$VERCEL_URL/rules answered $code, and it should be 200."
  # Where it redirects to identifies the problem without a build log. This app
  # sends signed-out visitors to /login and has no other auth route, so
  # anything else means the address belongs to a different project.
  target=$(curl -s -o /dev/null -w '%{redirect_url}' --max-time 20 "$VERCEL_URL/rules" || true)
  if [[ -n "$target" && "$target" != *"/login"* ]]; then
    printf '\n'
    warn "It redirected to $target — this app only ever sends people to /login,"
    warn "so that address is somebody else's deployment. Check the domain."
  else
    warn "Check the Vercel build log."
  fi
  confirm "Continue anyway?" || exit 1
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Supabase: point auth at the deployment"
say "This is the step that usually breaks a launch. Confirmation and"
say "password-reset links are built from the Site URL, so while that still"
say "says localhost they work for you and for nobody else."
open_url "$SUPABASE/auth/url-configuration"
printf '\n'
step "Set Site URL to:"
printf '    %s%s%s\n' "$BOLD" "$VERCEL_URL" "$RESET"
step "Under Redirect URLs, add:"
printf '    %s%s/**%s\n' "$BOLD" "$VERCEL_URL" "$RESET"
step "Leave http://localhost:3000 in the redirect list so local dev keeps working."
step "Save."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Supabase: decide on email confirmation"
say "Supabase's built-in mailer sends only a few messages an hour and often"
say "lands in spam. For a handful of friends that is a poor first impression."
printf '\n'
step "Off — friends sign up and are straight in. Reasonable for a private league."
step "On  — needs your own SMTP configured, or the confirmations will not arrive."
printf '\n'
open_url "$SUPABASE/auth/providers"
step "Open the Email provider and set 'Confirm email' to whichever you chose."
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "GitHub: the ingestion secrets"
say "Without these the daily job never runs — so after a race nothing is"
say "ingested, no price moves and no roster is scored."
open_url "https://github.com/$REPO/settings/secrets/actions"
printf '\n'
step "Confirm both of these exist, and add whichever does not:"
printf '    %sNEXT_PUBLIC_SUPABASE_URL%s\n' "$BOLD" "$RESET"
printf '    %sSUPABASE_SERVICE_ROLE_KEY%s\n' "$BOLD" "$RESET"
say "Both values are in your $ENV_FILE."
printf '\n'
say "Then check whether the job has ever actually run:"
open_url "https://github.com/$REPO/actions"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Supabase: rotate the database password"
say "The current one was pasted into a chat, so treat it as public."
printf '\n'
warn "This one is yours to do — I do not handle passwords."
printf '\n'
open_url "$SUPABASE/settings/database"
step "Database password → Reset database password → generate a new one."
step "Put it straight into your password manager."
step "Nothing in the app uses it. Only the Supabase CLI does, and it will ask"
step "for the new one next time you run 'npm run db:push'."
printf '\n'
if ! confirm "Rotated?"; then
  SKIPPED+=("rotate the database password")
fi
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Check it from the outside"
say "Signed out, the way a friend arrives."
printf '\n'

for path in / /rules /login; do
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 "$VERCEL_URL$path" || echo 000)
  if [[ "$code" == "200" ]]; then
    printf '  %s✓%s %-8s → 200\n' "$GREEN" "$RESET" "$path"
  else
    printf '  %s✗%s %-8s → %s\n' "$RED" "$RESET" "$path" "$code"
    SKIPPED+=("$path returned $code — check the Vercel build log")
  fi
done

# A signed-out visitor must not reach the pipeline page: it reads with the
# service role and renders whatever the database holds.
code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 "$VERCEL_URL/data" || echo 000)
if [[ "$code" == "200" ]]; then
  printf '  %s✗%s /data answered 200 while signed out — it should redirect\n' "$RED" "$RESET"
  SKIPPED+=("/data is reachable signed out — investigate before sharing the link")
else
  printf '  %s✓%s /data    is closed to visitors (%s)\n' "$GREEN" "$RESET" "$code"
fi

printf '\n'
say "Now sign up once yourself on the real domain, create a league, and send"
say "the invite code to one friend before you send it to everyone."

finish
